[package]
name = "vrento"
version = "0.1.0"
authors = ["hypengw <hypengwip@gmail.com>"]
license = "MIT OR Apache-2.0"

[lib]
name = "vrento"
module = "vrento.vulkan"
archive = "vrento"

[usage]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]

[dependencies]
rstd-std = { version = "0.1.0", pub = true }
rstd-cppstd = { version = "0.1.0", pub = true }
rstd-log = { version = "0.1.0", pub = true }
vvk = { git = "https://github.com/litocpp/vvk.git", pub = true }
wavsen = { git = "https://github.com/hypengw/wavsen.git" }
